# permissions for end users to edit cuberesourcequota.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cuberesourcequota-editor-role
rules:
  - apiGroups:
      - quota.kubecube.io
    resources:
      - cuberesourcequota
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - quota.kubecube.io
    resources:
      - cuberesourcequota/status
    verbs:
      - get
