# permissions for end users to view projects.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: project-viewer-role
rules:
- apiGroups:
  - tenant.kubecube.io
  resources:
  - projects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tenant.kubecube.io
  resources:
  - projects/status
  verbs:
  - get
