# refer to https://stackoverflow.com/questions/46142990/configure-minikube-kubernetes-webhook-authentication-authorization

apiVersion: v1
kind: Config
clusters:
  - name: warden
    cluster:
      certificate-authority: /etc/cube/ca/ca.crt        # 用来验证远程服务的 CA
      server: https://warden.kubecube-system.svc:7443/api/v1/warden/authenticate # 要查询的远程服务 URL。必须使用 'https'。 host network
# insecure-skip-tls-verify: true

# users 指代 API 服务的 Webhook 配置
users:
  - name: api-server
    user:
      client-certificate: /etc/cube/ca/tls.crt # Webhook 插件要使用的证书
      client-key: /etc/cube/ca/tls.key          # 与证书匹配的密钥

# kubeconfig 文件需要一个上下文（Context），此上下文用于本 API 服务器
current-context: webhook
contexts:
  - context:
      cluster: warden
      user: api-server
    name: webhook